name: Blue-Green-strategy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ARTIFACT_NAME: blue-nginx
  RESOURCE_GROUP: kmtest
  AKS_CLUSTER_NAME: kmtestaks
  
jobs:
  deployapp:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
 
      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy app
        uses: Azure/k8s-deploy@v5
        with:
          namespace: default
          manifests: |
            service.yaml
            blue-deploy.yaml
            ingress.yaml
          images: |
            kkmee0209/blue-nginx:v2.0     
          strategy: blue-green
          route-method: service
          action: deploy


  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: akspromotion
    steps:
      - run: echo asked for approval


  promotereject:
    runs-on: ubuntu-latest
    needs: [deployapp, approveapp]
    if: always()
    # environment: akspromotion
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
 
      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Promote App
        if: ${{ needs.approveapp.result == 'success' }}  # approveapp 작업이 성공한 경우에만 실행
        uses: Azure/k8s-deploy@v5
        with:
          action: promote
          namespace: default        
          manifests: |
            green-deploy.yaml
            service.yaml
            ingress.yaml
          strategy: blue-green
          images: |
            kkmee0209/blue-nginx:v2.0

      - name: Reject App
        if: ${{ needs.approveapp.result == 'failure' }} # approveapp 작업이 실패한 경우에만 실행
        uses: Azure/k8s-deploy@v5
        with:
          action: reject
          namespace: default
          manifests: |
            blue-deploy.yaml
            service.yaml
            ingress.yaml
          strategy: blue-green
          images: |
            kkmee0209/blue-nginx:v1.0

