name: Blue-Green-strategy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_REPO_NAME: kkmee0209/blue-nginx
  ARTIFACT_NAME: blue-nginx
  RESOURCE_GROUP: kmtest
  AKS_CLUSTER_NAME: kmtestaks
  
jobs:
  deployapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: kmtest
          cluster-name: kmtestaks

      - name: Deploy app
        uses: azure/k8s-deploy@v1.3
        with:
          namespace: default
          manifests: |
            service.yaml
            blue-deploy.yaml
            ingress.yaml
          strategy: blue-green
          images: |
            kkmee0209/blue-nginx:v2.0          
          route-method: service
          action: deploy

  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: akspromotion
    steps:
      - run: echo "Deployment complete. Waiting for approval to promote or reject."

  promotereject:
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: kmtest
          cluster-name: kmtestaks
          
      - name: Promote App
        uses: azure/k8s-deploy@v1.3
        if: ${{ github.event.deployment_status == 'success' }}  # 승인이 성공적인 경우
        with:
          manifests: |
            green-deploy.yaml
            service.yaml
            ingres.yaml
          strategy: blue-green
          images: |
            kkmee0209/blue-nginx:v3.0
          action: promote
  
      - name: Reject App
        uses: azure/k8s-deploy@v1.3
        if: ${{ github.event.deployment_status == 'failure' }}  # 승인이 실패한 경우
        with:
          manifests: |
            blue-deploy.yaml
            service.yaml
            ingress.yaml
          strategy: blue-green
          images: |
             kkmee0209/blue-nginx:v3.0
          action: reject

